export default {
  name: 'Họ Tên',
  phoneNumber: 'Số điện thoại',
  email: 'Email',
  password: 'Mật khẩu',
  maleText: 'Nam',
  femaleText: 'Nữ',
  registerButtonText: 'ĐĂNG KÍ',
  dayOfBirth: 'Ngày sinh',
  calendarConfirm: 'OK',
  calendarCancel: 'Cancel',
  calendarTitle: 'Ngày sinh',
  calendarFormat: 'DD-MM-YYYY',
  calendarMinDate: '01-01-1990',
};
